/*
 * Chris and Gijs 2016
 * No copy without permision!
 */
package galgje_gc;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Chris & Gijs
 */
public class GalgjeNederlands extends javax.swing.JFrame {

    String woordGuess;
    String woord;
    String[] woordArray;
    String[] antwoord;
    String letter;
    int fout = 0;
    int letterGoed = 0;

    /**
     * Creates new form Galgje
     */
    public GalgjeNederlands() {
        initComponents();

    }

    /**
     * %
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        start = new javax.swing.JButton();
        wButton = new javax.swing.JButton();
        qButton = new javax.swing.JButton();
        eButton = new javax.swing.JButton();
        rButton = new javax.swing.JButton();
        tButton = new javax.swing.JButton();
        yButton = new javax.swing.JButton();
        uButton = new javax.swing.JButton();
        iButton = new javax.swing.JButton();
        oButton = new javax.swing.JButton();
        pButton = new javax.swing.JButton();
        aButton = new javax.swing.JButton();
        sButton = new javax.swing.JButton();
        dButton = new javax.swing.JButton();
        fButton = new javax.swing.JButton();
        gButton = new javax.swing.JButton();
        hButton = new javax.swing.JButton();
        jButton = new javax.swing.JButton();
        kButton = new javax.swing.JButton();
        lButton = new javax.swing.JButton();
        zButton = new javax.swing.JButton();
        xButton = new javax.swing.JButton();
        cButton = new javax.swing.JButton();
        vButton = new javax.swing.JButton();
        bButton = new javax.swing.JButton();
        nButton = new javax.swing.JButton();
        mButton = new javax.swing.JButton();
        antwoordLabel = new javax.swing.JLabel();
        galg = new javax.swing.JLabel();
        winEnVerlies = new javax.swing.JLabel();
        guessWoord = new javax.swing.JButton();

        jDialog1.setAlwaysOnTop(true);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Galgje door Gijs & Chris");
        setPreferredSize(new java.awt.Dimension(1920, 1017));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        start.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        start.setText("start");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        getContentPane().add(start, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 550, 380, 180));
        start.getAccessibleContext().setAccessibleParent(start);

        wButton.setText("W");
        wButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wButtonActionPerformed(evt);
            }
        });
        getContentPane().add(wButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, -1, 66));

        qButton.setText("Q");
        qButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qButtonActionPerformed(evt);
            }
        });
        getContentPane().add(qButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, -1, 66));

        eButton.setText("E");
        eButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eButtonActionPerformed(evt);
            }
        });
        getContentPane().add(eButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, 66));

        rButton.setText("R");
        rButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rButtonActionPerformed(evt);
            }
        });
        getContentPane().add(rButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, -1, 66));

        tButton.setText("T");
        tButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tButtonActionPerformed(evt);
            }
        });
        getContentPane().add(tButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, -1, 66));

        yButton.setText("Y");
        yButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yButtonActionPerformed(evt);
            }
        });
        getContentPane().add(yButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, -1, 66));

        uButton.setText("U");
        uButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uButtonActionPerformed(evt);
            }
        });
        getContentPane().add(uButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, -1, 66));

        iButton.setText("I");
        iButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iButtonActionPerformed(evt);
            }
        });
        getContentPane().add(iButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, -1, 66));

        oButton.setText("O");
        oButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oButtonActionPerformed(evt);
            }
        });
        getContentPane().add(oButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, -1, 66));

        pButton.setText("P");
        pButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pButtonActionPerformed(evt);
            }
        });
        getContentPane().add(pButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 270, -1, 66));

        aButton.setText("A");
        aButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aButtonActionPerformed(evt);
            }
        });
        getContentPane().add(aButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, -1, 66));

        sButton.setText("S");
        sButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sButtonActionPerformed(evt);
            }
        });
        getContentPane().add(sButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, -1, 66));

        dButton.setText("D");
        dButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dButtonActionPerformed(evt);
            }
        });
        getContentPane().add(dButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, -1, 66));

        fButton.setText("F");
        fButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fButtonActionPerformed(evt);
            }
        });
        getContentPane().add(fButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, -1, 66));

        gButton.setText("G");
        gButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gButtonActionPerformed(evt);
            }
        });
        getContentPane().add(gButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, -1, 66));

        hButton.setText("H");
        hButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hButtonActionPerformed(evt);
            }
        });
        getContentPane().add(hButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, -1, 66));

        jButton.setText("J");
        jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, -1, 66));

        kButton.setText("K");
        kButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButtonActionPerformed(evt);
            }
        });
        getContentPane().add(kButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 360, -1, 66));

        lButton.setText("L");
        lButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lButtonActionPerformed(evt);
            }
        });
        getContentPane().add(lButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, -1, 66));

        zButton.setText("Z");
        zButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zButtonActionPerformed(evt);
            }
        });
        getContentPane().add(zButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, -1, 66));

        xButton.setText("X");
        xButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xButtonActionPerformed(evt);
            }
        });
        getContentPane().add(xButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, -1, 66));

        cButton.setText("C");
        cButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, -1, 66));

        vButton.setText("V");
        vButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vButtonActionPerformed(evt);
            }
        });
        getContentPane().add(vButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, -1, 66));

        bButton.setText("B");
        bButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bButtonActionPerformed(evt);
            }
        });
        getContentPane().add(bButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, -1, 66));

        nButton.setText("N");
        nButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nButtonActionPerformed(evt);
            }
        });
        getContentPane().add(nButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 440, -1, 66));

        mButton.setText("M");
        mButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mButtonActionPerformed(evt);
            }
        });
        getContentPane().add(mButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 440, -1, 66));

        antwoordLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        antwoordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(antwoordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 550, 60));

        galg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/galgje_gc/galgje foto's/gDeel11.png"))); // NOI18N
        getContentPane().add(galg, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 250, -1, -1));

        winEnVerlies.setFont(new java.awt.Font("AR CENA", 0, 36)); // NOI18N
        winEnVerlies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        winEnVerlies.setText("Druk op start om te beginnen.");
        getContentPane().add(winEnVerlies, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 1130, 110));

        guessWoord.setText("Raad het woord");
        guessWoord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guessWoordActionPerformed(evt);
            }
        });
        getContentPane().add(guessWoord, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 170, 390, 60));

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed

        this.start.setVisible(false);
        start();
    }//GEN-LAST:event_startActionPerformed

    private void qButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qButtonActionPerformed
        this.qButton.setVisible(false);
        letter = "q";
        letterTest();
    }//GEN-LAST:event_qButtonActionPerformed

    private void eButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eButtonActionPerformed
        this.eButton.setVisible(false);
        letter = "e";
        letterTest();
    }//GEN-LAST:event_eButtonActionPerformed

    private void rButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rButtonActionPerformed
        this.rButton.setVisible(false);
        letter = "r";
        letterTest();
    }//GEN-LAST:event_rButtonActionPerformed

    private void tButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tButtonActionPerformed
        this.tButton.setVisible(false);
        letter = "t";
        letterTest();
    }//GEN-LAST:event_tButtonActionPerformed

    private void yButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yButtonActionPerformed
        this.yButton.setVisible(false);
        letter = "y";
        letterTest();
    }//GEN-LAST:event_yButtonActionPerformed

    private void uButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uButtonActionPerformed
        this.uButton.setVisible(false);
        letter = "u";
        letterTest();
    }//GEN-LAST:event_uButtonActionPerformed

    private void iButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iButtonActionPerformed
        this.iButton.setVisible(false);
        letter = "i";
        letterTest();
    }//GEN-LAST:event_iButtonActionPerformed

    private void oButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oButtonActionPerformed
        this.oButton.setVisible(false);
        letter = "o";
        letterTest();
    }//GEN-LAST:event_oButtonActionPerformed

    private void pButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pButtonActionPerformed
        this.pButton.setVisible(false);
        letter = "p";
        letterTest();
    }//GEN-LAST:event_pButtonActionPerformed

    private void aButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aButtonActionPerformed
        this.aButton.setVisible(false);
        letter = "a";
        letterTest();
    }//GEN-LAST:event_aButtonActionPerformed

    private void sButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sButtonActionPerformed
        this.sButton.setVisible(false);
        letter = "s";
        letterTest();
    }//GEN-LAST:event_sButtonActionPerformed

    private void dButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dButtonActionPerformed
        this.dButton.setVisible(false);
        letter = "d";
        letterTest();
    }//GEN-LAST:event_dButtonActionPerformed

    private void fButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fButtonActionPerformed
        this.fButton.setVisible(false);
        letter = "f";
        letterTest();
    }//GEN-LAST:event_fButtonActionPerformed

    private void gButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gButtonActionPerformed
        this.gButton.setVisible(false);
        letter = "g";
        letterTest();
    }//GEN-LAST:event_gButtonActionPerformed

    private void hButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hButtonActionPerformed
        this.hButton.setVisible(false);
        letter = "h";
        letterTest();
    }//GEN-LAST:event_hButtonActionPerformed

    private void jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActionPerformed
        this.jButton.setVisible(false);
        letter = "j";
        letterTest();
    }//GEN-LAST:event_jButtonActionPerformed

    private void kButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButtonActionPerformed
        this.kButton.setVisible(false);
        letter = "k";
        letterTest();
    }//GEN-LAST:event_kButtonActionPerformed

    private void lButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lButtonActionPerformed
        this.lButton.setVisible(false);
        letter = "l";
        letterTest();
    }//GEN-LAST:event_lButtonActionPerformed

    private void wButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wButtonActionPerformed
        this.wButton.setVisible(false);
        letter = "w";
        letterTest();
    }//GEN-LAST:event_wButtonActionPerformed

    private void zButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zButtonActionPerformed
        this.zButton.setVisible(false);
        letter = "z";
        letterTest();
    }//GEN-LAST:event_zButtonActionPerformed

    private void xButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xButtonActionPerformed
        this.xButton.setVisible(false);
        letter = "x";
        letterTest();
    }//GEN-LAST:event_xButtonActionPerformed

    private void cButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButtonActionPerformed
        this.cButton.setVisible(false);
        letter = "c";
        letterTest();
    }//GEN-LAST:event_cButtonActionPerformed

    private void vButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vButtonActionPerformed
        this.vButton.setVisible(false);
        letter = "v";
        letterTest();
    }//GEN-LAST:event_vButtonActionPerformed

    private void bButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bButtonActionPerformed
        this.bButton.setVisible(false);
        letter = "b";
        letterTest();
    }//GEN-LAST:event_bButtonActionPerformed

    private void nButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nButtonActionPerformed
        this.nButton.setVisible(false);
        letter = "n";
        letterTest();
    }//GEN-LAST:event_nButtonActionPerformed

    private void mButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mButtonActionPerformed
        this.mButton.setVisible(false);
        letter = "m";
        letterTest();
    }//GEN-LAST:event_mButtonActionPerformed

    private void guessWoordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guessWoordActionPerformed
        woordGuess = JOptionPane.showInputDialog("vul hier uw woord in");
        woordTest();
    }//GEN-LAST:event_guessWoordActionPerformed

    /**
     * @param args the command line arguments
     */
    public void start() {
        //woord invullen en array lengtens zetten
        woord = JOptionPane.showInputDialog("vul hier uw woord in");
        woordArray = new String[woord.length()];
        antwoord = new String[woord.length()];
        
        // alles restetten
        this.aButton.setVisible(true);
        this.bButton.setVisible(true);
        this.cButton.setVisible(true);
        this.dButton.setVisible(true);
        this.eButton.setVisible(true);
        this.fButton.setVisible(true);
        this.gButton.setVisible(true);
        this.hButton.setVisible(true);
        this.iButton.setVisible(true);
        this.jButton.setVisible(true);
        this.kButton.setVisible(true);
        this.lButton.setVisible(true);
        this.mButton.setVisible(true);
        this.nButton.setVisible(true);
        this.oButton.setVisible(true);
        this.pButton.setVisible(true);
        this.qButton.setVisible(true);
        this.rButton.setVisible(true);
        this.sButton.setVisible(true);
        this.tButton.setVisible(true);
        this.uButton.setVisible(true);
        this.vButton.setVisible(true);
        this.wButton.setVisible(true);
        this.xButton.setVisible(true);
        this.yButton.setVisible(true);
        this.zButton.setVisible(true);
        fout = 0;
        winEnVerlies.setText("");

        
        galg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/galgje_gc/galgje foto's/gDeel0.png")));
        
        //woord letter voor letter in array zetten
        for (int i = 0; i < woord.length(); i++) {
            woordArray[i] = woord.substring(i, i + 1);
        }
        // voor elke letter een _ zetten
        for (int i = 0; i < antwoord.length; i++) {
            antwoord[i] = "_";
        }
        //alle - al in het woord zetten zodat je dat niet hoeft te raden 
        for (int i = 0; i < woordArray.length; i++) {
            if (woordArray[i].equals("-")) {
                antwoord[i] = "-";
            }
        }
        //het andwoord in de label zetten
        antwoordLabel.setText("");
        for (int i = 0; i < antwoord.length; i++) {
            antwoordLabel.setText(antwoordLabel.getText() + antwoord[i] + " ");
            
        }
    }

    public void woordTest() {
        //kijken of het geraden woord klopt met het woord
        if (woordGuess.equals(woord)) {
            for (int i = 0; i < antwoord.length; i++) {
                antwoord[i] = woordArray[i];
            }

        } else {
            fout = fout + 1;
        }
        goedFout();
    }

    public void letterTest() {
        // kijken of de letter die je hebt ingevuld in het woord staat
        int goed = 0;
        for (int i = 0; i < antwoord.length; i++) {
            if (letter.equals(woordArray[i])) {
                antwoord[i] = letter;
                goed = goed + 1;
            }
        }
        //kijken of de letter er minimaal 1 keer in staat
        if (goed < 1) {
            fout = fout + 1;
        }
        goedFout();
    }

    public void antwoordTest() {
        //kijken of het woord goed is
        letterGoed = 0;
        for (int i = 0; i < antwoord.length; i++) {
            if (woordArray[i].equals(antwoord[i])) {
                letterGoed = letterGoed + 1;

            }
        }

    }

    public void goedFout() {

        //letter invullen en letters uitprinten
        if (fout < 11) {
            //gerade letters invullen
            antwoordLabel.setText("");
            for (int i = 0; i < antwoord.length; i++) {
                antwoordLabel.setText(antwoordLabel.getText() + antwoord[i] + " ");

            }
            antwoordTest();
            //als het woord goed is dat melden in de label 
            if (letterGoed == woordArray.length) {
                winEnVerlies.setFont(new java.awt.Font("Comic Sans MS", 0, 36));
                winEnVerlies.setForeground(Color.green);
                winEnVerlies.setText("U heeft gewonnen. Druk op start om opnieuw te spelen.");
                this.start.setVisible(true);

            }
            //het plaatje veranderen naarmate hoeveel fouten je hebt gemaakt
           galg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/galgje_gc/galgje foto's/gDeel" + fout +".png")));
            
        } else {
             //als je hebt verloren dat melden in de label
            galg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/galgje_gc/galgje foto's/gDeel11.png")));
            antwoordLabel.setText(woord);
            winEnVerlies.setFont(new java.awt.Font("Chiller", 0, 36));
            winEnVerlies.setForeground(Color.red);
            winEnVerlies.setText("U heeft verloren. Druk op start om opnieuw te spelen.");
            this.start.setVisible(true);
        }

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GalgjeNederlands.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GalgjeNederlands.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GalgjeNederlands.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GalgjeNederlands.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GalgjeNederlands().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aButton;
    private javax.swing.JLabel antwoordLabel;
    private javax.swing.JButton bButton;
    private javax.swing.JButton cButton;
    private javax.swing.JButton dButton;
    private javax.swing.JButton eButton;
    private javax.swing.JButton fButton;
    private javax.swing.JButton gButton;
    private javax.swing.JLabel galg;
    private javax.swing.JButton guessWoord;
    private javax.swing.JButton hButton;
    private javax.swing.JButton iButton;
    private javax.swing.JButton jButton;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JButton kButton;
    private javax.swing.JButton lButton;
    private javax.swing.JButton mButton;
    private javax.swing.JButton nButton;
    private javax.swing.JButton oButton;
    private javax.swing.JButton pButton;
    private javax.swing.JButton qButton;
    private javax.swing.JButton rButton;
    private javax.swing.JButton sButton;
    private javax.swing.JButton start;
    private javax.swing.JButton tButton;
    private javax.swing.JButton uButton;
    private javax.swing.JButton vButton;
    private javax.swing.JButton wButton;
    private javax.swing.JLabel winEnVerlies;
    private javax.swing.JButton xButton;
    private javax.swing.JButton yButton;
    private javax.swing.JButton zButton;
    // End of variables declaration//GEN-END:variables
}
